### ISSUE TITLE
Infografia de ciclos del software y modelos de ciclos del software

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-1-infografia-abicoronel#2]
[Ciclo del software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-abicoronel/files/9421824/Ciclo.del.software.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
